# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      # All non-bat files should end with LF
      - id: mixed-line-ending
        name: Ensure LF endings on most files
        args: ["--fix=lf"]
        exclude: \.bat$
      # Bat files should end with CRLF
      - id: mixed-line-ending
        name: Ensure CFLF endings on Windows files
        args: ["--fix=crlf"]
        files: \.bat$
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/ioxio-dataspace/ioxio-data-product-definition-tooling
    rev: 0.3.0
    hooks:
      - id: data-product-definition-converter
        # TODO: convert only the file that was changed
        pass_filenames: false
        args: ["src", "DataProducts"]
        files: |
          (?x)^(
            DataProducts/.*json|
            src/.*py
          )$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/omarudolley/openapi-to-fastapi.git
    rev: "feature/update-pydantic-fastapi-datamodel-code-generator"
    hooks:
      - id: openapi-validator
        files: ".*?DataProducts/.*?json$"
        args: ["--path", "./DataProducts"]
  - repo: https://github.com/TheHelias/data-product-definition-tooling
    rev: "feat/pydantic-2"
    hooks:
      - id: data-product-definition-validator
        files: ".*?DataProducts/.*?json$"
        args: ["./DataProducts"]
